language: cpp

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - mkdir build
  - cd build
  - cmake -DINSTDIR:STRING=~/services -DDEFUMASK:STRING=077 -DCMAKE_BUILD_TYPE:STRING=DEBUG -DUSE_RUN_CC_PL:BOOLEAN=ON ..

script:
  - make

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - debian-sid
    packages:
    - cmake
    - cmake-data
    - gcc-4.8-base
    - gcc-4.8
    - libstdc++-4.8-dev
    - libcloog-isl4
    - libisl15
    - libmpc3
    - libmpfr4

notifications:
  irc:
    - "irc.cleverpun#irc"
